Logging:
  Level: Verbose # Verbose, Debug, Information, Warning, Fatal

Dirs:
  Fragments: Content
  Templates: Templates
  Output: Public
  Assets: Assets
  AssetsOutput: Assets
  
Site:
  Title: My Awesome Title